version: '3.8'

services:
  web:
    build: .
    container_name: flask_aws_app
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./static/faces:/app/static/faces
      - .:/app